name: Deploy Express Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.EXPRESS_DEPLOY_PRIVATE_KEY }}
        HOST: 103.241.64.253
        USER: root
        APP_DIR: ~/apps/face-reality-api/
      run: |
        echo "$PRIVATE_KEY" > deploy_key
        chmod 600 deploy_key
        
        # Use rsync to deploy the application excluding the .env and img folders
        rsync -avz --delete --exclude '.env' --exclude 'img/' -e "ssh -i deploy_key -o StrictHostKeyChecking=no" ./ $USER@$HOST:$APP_DIR
        
        # SSH into the server and restart the application
        ssh -i deploy_key $USER@$HOST "source ~/.nvm/nvm.sh && nvm use 18 && cd $APP_DIR && npm install && pm2 restart face-reality-api"
